<?php
function fjm_merce_menu() {
  $items = array();
  $items['home'] = array(
    'title' => t('Home'),
    'page callback' => 'fjm_merce_landing_page',  
    'access arguments' => array('access content'),
    'file' => 'fjm_merce_landing.page.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function fjm_merce_theme($existing, $type, $theme, $path) {
  return array(
    'fjm_merce_landing' => array(
      'path' => drupal_get_path('module', 'fjm_merce') . '/templates',
      'arguments' => array(
        'menu' => NULL,
        'carousel' => NULL,
        'bio' => NULL,
        'browse' => NULL,
        'search_form' => NULL,
      ),
      'template' => 'fjm_merce_landing_page',
    ),
    'fjm_merce_bio' => array(
      'arguments' => array(
        'text' => NULL,
      ),
    ),
    'fjm_merce_menu' => array(
      'arguments' => array(
        'menu_links' => NULL,
      ),
    ),
    'fjm_merce_browse' => array(
      'arguments' => array(
        'photo_albums' => NULL,
        'recordings' => NULL,
        'press_clippings' => NULL,
      ),
    ),
    'fjm_merce_audio' => array(
      'path' => drupal_get_path('module', 'fjm_merce') . '/templates',
        'arguments' => array(
          'mods_data' => NULL,
        ),
        'template' => 'fjm_merce_audio_object',
    ),
    'fjm_merce_mods' => array(
      'arguments' => array(
        'mods_data' => NULL,
      ),
    ),
  );
}

function fjm_merce_required_fedora_objects() {
  $module_path = drupal_get_path('module', 'fjm_merce');
  
  return array(
    'fjm_merce' => array(
      'module' => 'fjm_merce',
      'title' => 'FJM Merce',
      'objects' => array(
        array(
          'pid' => 'cam:photoCModel',
          'label' => 'Photo Content Model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/PHOTOCM.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'cam:collectionRecordings',
          'label' => 'Coleccion Antonia Merce Recordings',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/recordings/COLLECTION-POLICY.xml",
            ),
          ),
        ),
        array(
          'pid' => 'cam:collectionClippings',
          'label' => 'Coleccion Antonia Merce Clippings',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/clippings/COLLECTION-POLICY.xml",
            ),
          ),
        ),
        array(
          'pid' => 'cam:collectionAlbums',
          'label' => 'Coleccion Antonia Merce Photo Albums',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/albums/COLLECTION-POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}


function theme_fjm_merce_bio($text) {
  return $text;
}

function theme_fjm_merce_menu($menu_links) {
  $menu = theme('links', $menu_links, array('class' => 'fjm-merce-menu'));
  
  return $menu;
}

function theme_fjm_merce_browse($photo_albums, $recordings, $press_clippings) {
  $output = '<div class="browse-links">';
  $output .= '<h2>' . t('Photo Albums') . '</h2>';
  $output .= theme('links', $photo_albums, array('class' => 'fjm-merce-photo-albums'));
  $output .= '</div>';
  $output .= '<div class="browse-links">';
  $output .= '<h2>' . t('Recordings') . '</h2>';
  $output .= theme('links', $recordings, array('class' => 'fjm-merce-recordings'));
  $output .= '</div>';
  $output .= '<div class="browse-links last">';
  $output .= '<h2 class="last">' . t('Press Clippings') . '</h2>';
  $output .= theme('links', $press_clippings, array('class' => 'fjm-merce-press-clippings last'));
  $output .= '</div>';
  
  return $output;
}

function theme_fjm_merce_mods($mods_data) {
  $items = array();
  foreach ($mods_data AS $mods) {
    $items[] = '<label>' . t($mods['title']) . '</label><span>' . $mods['value'] . '</span>';
  }
  
  $output = theme_item_list($items, NULL, 'ul', array('class' => 'metadata'));
  
  return $output;
}

function fjm_merce_render_mods($mods_xml_file) {
  $mods_xml = simplexml_load_string($mods_xml_file);
  $mods_xml->registerXPathNamespace('mods', 'http://www.loc.gov/mods/v3');

  $mods_fields = array();

  $date = $mods_xml->xpath('//mods:dateCreated[1]');
  $authors = $mods_xml->xpath('//mods:name/mods:displayForm');
  $topics = $mods_xml->xpath('//mods:subject/mods:topic');
  $physical_description = $mods_xml->xpath('//mods:physicalDescription/mods:note');
  $notes = $mods_xml->xpath('mods:note');

  $count = 0;

  $mods_fields = _fjm_merce_merge_mods($mods_fields, 'Date', $date, $count);
  $mods_fields = _fjm_merce_merge_mods($mods_fields, 'Author', $authors, $count);
  $mods_fields = _fjm_merce_merge_mods($mods_fields, 'Topic', $topics, $count);
  $mods_fields = _fjm_merce_merge_mods($mods_fields, 'Physical Description', $physical_description, $count);
  $mods_fields = _fjm_merce_merge_mods($mods_fields, 'General Note', $notes, $count);

  return $mods_fields;
}

function _fjm_merce_merge_mods($mods_fields, $title, $values, &$count) {
  if (($values)) {
    foreach ($values AS $value) {
      $mods_fields[$count]['title'] = t($title); // Needs proper translation
      $mods_fields[$count]['value'] = (string) $value;
      $count++;
    }
  }
  return $mods_fields;
}